apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-manager-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-manager
  template:
    metadata:
      labels:
        app: inventory-manager
    spec:
      containers:
        - name: inventory-manager
          image: inventory-manager-k8s
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "your-external-db-ip"
            - name: DB_PORT
              value: "5432" # or your database's port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_PASSWORD
            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: API_SECRET_KEY
          readinessProbe:
            httpGet:
              path: /login
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10