global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

#  - job_name: 'cadvisor'
#    dns_sd_configs:
#    - names:
#      - 'tasks.cadvisor'
#      type: 'A'
#      port: 8090

  - job_name: 'flask-api'
    dns_sd_configs:
      - names:
        - 'tasks.app'
        type: 'A'
        port: 5000